version: '2'
services:
  db:
    image: mongo:4.2
    volumes:
      - /var/lib/mongodb:/data/db
  dispotrains:
    build: .
    command: /usr/bin/supervisord
    ports:
      - "9000:9000"
    links:
      - db
    volumes:
      - /home/web/dispotrains/key:/dispotrains/key
      - /home/web/dispotrains/data:/dispotrains/build/static/data
