version: '2'
services:
  dispotrains:
    build: .
    command: /usr/bin/supervisord
    ports:
      - "9000:9000"
    volumes:
      - /home/web/dispotrains/key:/dispotrains/key
      - /home/web/dispotrains/data:/dispotrains/static/data
      - /home/web/dispotrains/db:/dispotrains/db
    restart: unless-stopped
    networks:
      dispotrains_net:
networks:
  dispotrains_net:
    driver: bridge
